### ISSUE TITLE
TST: Actions wish list

### ISSUE THREAD

**Issue by pllim** [spacetelescope/synphot_refactor#195]
These were not possible when #194 (Azure) or #260 (Actions) was done. Maybe revisit in the future:

- [x] See if `pytest` warnings would bubble up to GitHub checks summary. (No longer relevant)
- [x] See if `[skip ci]` can support skipping CI in a PR. #289 
- [x] See if `[skip ci]` can be ignored when PR is merged into `master`. #289 
- [x] `codecov` coverage report for PR, not just `master`.
- [x] Allow astropy dev job to fail (maybe; this was not even done here in Travis CI days). (No longer relevant)
- [x] Add a Sphinx link check cron job.
- [x] ~Preview doc artifact as static webpage (maybe; this was not even done here in Travis CI days).~ Not needed anymore; RTD can do it now. See #214 

xref: Notes in astropy/astropy#8445
