### ISSUE TITLE
Impact of renaming CDBS

### ISSUE THREAD

**Issue by pllim** [spacetelescope/synphot_refactor#270]
RedCat has plans to rename CDBS (possibly to TRDS, see https://jira.stsci.edu/browse/REDCAT-111).

**Affected code**

* Documentation:
    - [x] Example paths need to be updated. See #278 
* Code:
    - [x] Defaults in `config` need to be updated. This also means that server needs updating. See #278 
    - [x] `BASE_HOST` in `utils.py` needs to be updated. See #278 
    * Mentions of `cdbs` in test variables can be updated but not compulsory, as these are not user-facing. (No change)

**Action items**

- [x] Make changes to package as documented above. See #278 
- [x] Make a software release with bump to major version.
- [x] ~Add a note/warning to package front page about this change.~ There is very little user-facing change, so not needed.
- [x] ~Add a pinned issue about this change.~ There is very little user-facing change, so not needed.

cc @rizeladiaz and @vglaidler 

xref spacetelescope/pysynphot#131 and spacetelescope/stsynphot_refactor#114
